### ISSUE TITLE
MacOS 11.1 Run Issues

### ISSUE THREAD

**Issue by margot-l** [esgibter/fandomstats#90]
Hi,
I'm trying to get this to work on my Mac 11.1 because I think this is really cool but have run into three errors.

`dev_appserver.py src/` works but `gcloud preview app run src/app.yaml` leads to:

> gcloud preview app run app.yaml
> ERROR: (gcloud) Invalid choice: 'preview'.
> Maybe you meant:
>   gcloud app
> 
> To search the help text of gcloud commands, run:
>   gcloud help -- SEARCH_TERMS

When I run the tests I get:
 

> /Library/Python/2.7/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (dev) or chardet (3.0.4) doesn't match a supported version!
>   RequestsDependencyWarning)
> test_getUrl_UTF8 (Ao3url_test.Ao3urlTestCase) ... ok
> test_getUrl_basic (Ao3url_test.Ao3urlTestCase) ... ok
> test_getUrl_complex (Ao3url_test.Ao3urlTestCase) ... ok
> test_getUrl_moderately_complex (Ao3url_test.Ao3urlTestCase) ... ok
> test_getUrl_other_tag_names (Ao3url_test.Ao3urlTestCase) ... ok
> test_setFilters (Ao3url_test.Ao3urlTestCase) ... ok
> test_fetchHTML_basic (Ao3data_test.Ao3dataTestCase) ... skipped 'not yet'
> test_fetchHTML_nonexistent_tag (Ao3data_test.Ao3dataTestCase) ... ok
> test_fetchHTML_very_bad_url (Ao3data_test.Ao3dataTestCase) ... ok
> test_bracket_tags (integration_api_basic_test.ApiTest) ... ok
> test_bracket_tags_mixed (integration_api_basic_test.ApiTest) ... ok
> test_multiple_tags (integration_api_basic_test.ApiTest) ... ok
> test_nonexistent_tag (integration_api_basic_test.ApiTest) ... ok
> test_simple_call (integration_api_basic_test.ApiTest) ... ok
> test_synonym_tag (integration_api_basic_test.ApiTest) ... skipped 'currently untestable - aborts internally and throws an error'
> integration_api_params_test (unittest.loader.ModuleImportFailure) ... ERROR
> 
> ======================================================================
> ERROR: integration_api_params_test (unittest.loader.ModuleImportFailure)
> ----------------------------------------------------------------------
> ImportError: Failed to import test module: integration_api_params_test
> Traceback (most recent call last):
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
>     module = self._get_module_from_name(name)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
>     __import__(name)
>   File "/Users/margotlautens/Downloads/fandomstats-master/src/tests/integration_api_params_test.py", line 5, in <module>
>     import requests
>   File "/Library/Python/2.7/site-packages/requests/__init__.py", line 111, in <module>
>     from urllib3.exceptions import DependencyWarning
> ImportError: cannot import name DependencyWarning
> 
> 
> ----------------------------------------------------------------------
> Ran 16 tests in 6.050s
> 
> FAILED (errors=1, skipped=2)

Meanwhile `appcfg.py update src/` leads to `appcfg.py: command not found` since it's been deprecated but using `gcloud app update src/` creates the error 

> ERROR: (gcloud.app.deploy) The required property [project] is not currently set.
> You may set it for your current workspace by running:
> 
>   $ gcloud config set project VALUE
> 
> or it can be set temporarily by the environment variable [CLOUDSDK_CORE_PROJECT]

I thought this might be the project ID that you mention might need to be set which is in the app.yaml but I can't find it anywhere.

Best,
Margot

**Comment by annathecrow** [comment]
Hi,

as for the first problem, try running it without the `preview` keyword, e.g. `gcloud preview app run src/app.yaml`. AFAIK `preview` is a command subtree that is used for commands that aren't "official" yet, so it's possible they have been graduated to official since we wrote the README. If `dev_appserver.py src/` works, you can just keep using that, they should be identical.

The tests... that looks like broken dependency versions. Are you using a virtualenv? I'd try creating a clean one and installing the dependencies again, to make sure everything downloaded properly.
Other possible problem that I can think of is that our dependency list doesn't have version numbers. Maybe the currently newest versions of the required libs are not compatible anymore. 

As for the last error, that command is used to upload the code to GCloud so it's accessible online, so that won't work for you. If you want to play around with the project, you don't need it, you can just run it locally and it will work just as well (or better) than online. Unless you want to run your own public fork, I guess? Then you would need to set up GCloud account of your own to publish on. That's... a completely different kettle of fish, honestly, and I'm really not someone who can give advice about it.

Anyway, it's really neat that you're interested in the code! If you have more questions, let me know, I'll try to answer what I can.
